"""Shared paths and helpers for the reproduction tools.

Everything resolves relative to the repository root, so the checkout can live
anywhere. No tool in this directory fits a model or reads the source dataset.
"""
from __future__ import annotations

import hashlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "report"
SHARED = REPORT / "shared"
DATA = SHARED / "data"
FIGURES = SHARED / "figures"
TABLES = SHARED / "tables"
BUILD = ROOT / "build"
LANGS = ("zh", "en")

#: Files copied from report/shared into each language directory before compiling.
SHARED_TEX = ("preamble.tex", "equations.tex", "references.bib")
#: Figure basenames the report includes.
FIGURE_NAMES = (
    "fig01_method",
    "fig02_rmse",
    "fig03_proxy",
    "fig04_main",
    "fig05_ensemble",
    "fig06_daily",
)
#: Tables generated by report/shared/build_tables.py.
TABLE_NAMES = (
    "main_results",
    "paired",
    "bags",
    "selection_control",
    "provenance",
    "correlations",
    "bootstrap",
)


def sha(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def run(cmd: list[str], cwd: Path | None = None) -> None:
    """Run a subprocess, echoing the command and failing loudly."""
    print("  $ " + " ".join(str(c) for c in cmd), flush=True)
    result = subprocess.run([str(c) for c in cmd], cwd=str(cwd or ROOT))
    if result.returncode != 0:
        raise SystemExit(f"command failed with exit code {result.returncode}")


def generate_tables(scratch: Path) -> Path:
    """Run report/shared/build_tables.py into a scratch tree and return it.

    build_tables.py expects <root>/shared/data as input and writes
    <root>/<lang>/tables, so the scratch tree mirrors that shape.
    """
    if scratch.exists():
        shutil.rmtree(scratch)
    (scratch / "shared").mkdir(parents=True)
    shutil.copytree(DATA, scratch / "shared" / "data")
    for lang in LANGS:
        (scratch / lang / "tables").mkdir(parents=True)
    run([python(), str(SHARED / "build_tables.py"), "--root", str(scratch)])
    return scratch


def stage(dest_root: Path) -> None:
    """Assemble self-contained zh/ and en/ trees from report/shared.

    report/shared is the single source of truth; the language directories hold
    only main.tex and author.tex in version control. This mirrors what the
    Overleaf packages need without committing three copies of the same records.
    """
    for lang in LANGS:
        dest = dest_root / lang
        (dest / "data").mkdir(parents=True, exist_ok=True)
        (dest / "figures").mkdir(parents=True, exist_ok=True)
        (dest / "tables").mkdir(parents=True, exist_ok=True)
        (dest / "scripts").mkdir(parents=True, exist_ok=True)
        for name in ("main.tex", "author.tex"):
            shutil.copy2(REPORT / lang / name, dest / name)
        for name in SHARED_TEX:
            shutil.copy2(SHARED / name, dest / name)
        for item in sorted(DATA.iterdir()):
            if item.suffix in (".csv", ".json"):
                shutil.copy2(item, dest / "data" / item.name)
        for name in FIGURE_NAMES:
            shutil.copy2(FIGURES / f"{name}.pdf", dest / "figures" / f"{name}.pdf")
        for name in TABLE_NAMES:
            shutil.copy2(TABLES / lang / f"{name}.tex", dest / "tables" / f"{name}.tex")
        for name in ("build_figures.py", "build_tables.py", "derive_records.py"):
            shutil.copy2(SHARED / name, dest / "scripts" / name)
        for name in ("requirements.txt", "requirements-audit.txt"):
            shutil.copy2(ROOT / name, dest / "scripts" / name)
        (dest / ".latexmkrc").write_text(
            '$pdf_mode = 5;\n$xelatex = "xelatex -interaction=nonstopmode -halt-on-error %O %S";\n',
            encoding="utf-8",
        )


def find_engine() -> list[str]:
    """Return the LaTeX command prefix, preferring Tectonic then latexmk."""
    for name in ("tectonic",):
        found = shutil.which(name)
        if found:
            return [found, "-X", "compile"]
    if shutil.which("latexmk"):
        return ["latexmk", "-xelatex", "-interaction=nonstopmode"]
    raise SystemExit(
        "No LaTeX engine found. Install Tectonic (https://tectonic-typesetting.github.io) "
        "or a TeX Live distribution providing latexmk + xelatex, then re-run.\n"
        "To read the report without compiling, open report/pdf/."
    )


def compile_tex(source_dir: Path, out_dir: Path) -> Path:
    """Compile source_dir/main.tex into out_dir and return the PDF path."""
    out_dir.mkdir(parents=True, exist_ok=True)
    engine = find_engine()
    if engine[0].endswith("latexmk") or engine[0] == "latexmk":
        run(engine + [f"-outdir={out_dir}", str(source_dir / "main.tex")], cwd=source_dir)
    else:
        run(engine + [str(source_dir / "main.tex"), "--outdir", str(out_dir),
                      "--keep-intermediates", "--keep-logs"])
    pdf = out_dir / "main.pdf"
    if not pdf.is_file():
        raise SystemExit(f"compilation produced no PDF at {pdf}")
    return pdf


def python() -> str:
    return sys.executable
